### ISSUE TITLE
Color error in the (popup) list

### ISSUE THREAD

**Issue by FreePDF64** [2alin/tabFx#1]
If I have many tabs in the list as an example and scroll down to the last entry, move the mouse back and return (sometimes several times) between the last and penultimate entry, I have a color error in the list. Please see as example the following pictures:

![color issue](https://user-images.githubusercontent.com/38452654/38851608-a9ba1292-4216-11e8-9459-f1dc2168b3de.jpg)

![color issue2](https://user-images.githubusercontent.com/38452654/38851727-30c7877e-4217-11e8-9183-ac6fca66b55c.jpg)

I use Windows 10 Pro 64bit - and this color error is visible on all Windows PCs (MS Surface, hp-PC's, etc.).
I use the latest graphic drivers.

Kind regards,
Michael

**Comment by FreePDF64** [comment]
Here you see a short video to this color error:

[TabFX.zip](https://github.com/2alin/tabFx/files/1919690/TabFX.zip)

**Comment by 2alin** [comment]
Thank you for the pictures and video as well, that helped me find out about the problem, and I think it's fixed. 

Could you please try this experimental version: 
https://addons.mozilla.org/firefox/addon/tabfx-experimental/

and let me know if the problem is fixed, so I can update the original tabFx extension.
