### ISSUE TITLE
search

### ISSUE THREAD

**Issue by gherghel** [2alin/tabFx#14]
Worked fine until today.
But beginning with 16 August 2023 SEARCH function is dead.
I am using Firefox 118.

**Comment by gherghel** [comment]
it was a strange bug, because after a couple of hours, it fixed by itself.

**Comment by 2alin** [comment]
@gherghel Thanks for reporting the issue you encountered.

I answered the comment you left in your extension's review at https://addons.mozilla.org/en-US/firefox/addon/tab-fx/reviews/. Like I mentioned there, it looks like you are using a Nightly version of Firefox, so it's quite normal for things to break there due to the browser functionality and not the extension. I'm happy that the people at Firefox were fast to resolve any broken functionality. 

I'll mark this ticket as closed, as the issue is no more present.

**Comment by gherghel** [comment]
It came back.
The search function does not work (it is empty) though I have hundreds of tabs.
Reinstall the application does not help.
W11
Firefox 124
