### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by gherghel** [2alin/tabFx#16]
Tabs are not loading.

W11
Firefox 129

**Comment by gherghel** [comment]
After 10 hours the extension returned to normal.

**Comment by gherghel** [comment]
Periodically this problem returns.
Why?

**Comment by 2alin** [comment]
Closing this issue as I have mentioned already to the reporter that the reason the extension breaks often to them is due to being used in Firefox Nightly which the extension won't keep up due to being a very unstable environment.

See my previous comments:
https://github.com/2alin/tabFx/issues/14#issuecomment-1680429145
https://github.com/2alin/tabFx/issues/15#issuecomment-1937914897
