### ISSUE TITLE
Loading  problem

### ISSUE THREAD

**Issue by gherghel** [2alin/tabFx#18]
Tabs are not loading in search mode.
Windows 11, Firefox 131.

The issue lasted for 24 hours, after which it resolved.

This problem occurs periodically.

Why don't you collaborate with Firefox developers to fix this bug?

**Comment by 2alin** [comment]
Closing this issue as I have mentioned already to the reporter that the reason the extension breaks often with them is due to being used in Firefox Nightly which the extension won't keep up due to being a very unstable environment.

See my previous comments:
https://github.com/2alin/tabFx/issues/14#issuecomment-1680429145
https://github.com/2alin/tabFx/issues/15#issuecomment-1937914897
