### ISSUE TITLE
Search in bookmarks/history and display total number of tabs

### ISSUE THREAD

**Issue by FreePDF64** [2alin/tabFx#3]
Hi,
is it possible to make wishes for implementation into tabfx (like: search also in bookmarks and history, display total number of tabs also above the popup icon)?

Kind regards,
Michael

**Comment by 2alin** [comment]
Yes, it is possible. It's the same procedure as the issue but adding the label 'enhancement', then writing a brief request title and a longer description about it.

I already added the label, and modified the title so the requests you described are visible there. Hope you don't mind.

Now, about what you suggested. I had thought on it already, but I decided not to add them, the reasons are:
*  I want the extension to be clean, light and fast. Main focus on opened tabs and only that. If I add the bookmarks and history batch into the search engine, it will be slower and the filtered list less clean.

* And about the counter badger (above the popup icon), I don't like counter badgers xD, they distract me a lot when I'm reading. And I want the extension to be as silent an quiet as possible — that's why my extension doesn't have any background script running all the time (many other listings tabs have it), it only runs when the pop-up is opened and that's all. 

Of course, I could change my mind in the near future and add settings that could enable/disable what you asked for. That's why I will let this request opened for a while and analyse it again soon.

Thank you for your suggestions, Michael, and have a nice day!

**Comment by 2alin** [comment]
I haved opened #12 to follow the requested feature of a badge displaying the amount of opened tabs. 

And as the other feature (search in bookmark/history) is currently outside the scope of tabFx desired purpose (handling current opened tabs), I have decided to close this issue.
